/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 29-3-2013 22:54:36
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeaponRackDetailLeather extends ModelBase
{
    //fields
    ModelRenderer pouch1;
    ModelRenderer pouch2;
    ModelRenderer pouch3;
    ModelRenderer pouch4;

    public ModelWeaponRackDetailLeather()
    {
        textureWidth = 32;
        textureHeight = 32;

        pouch1 = new ModelRenderer(this, 0, 0);
        pouch1.addBox(-3F, 0F, 0F, 5, 7, 3);
        pouch1.setRotationPoint(6F, 17.2F, 5F);
        pouch1.setTextureSize(32, 32);
        pouch1.mirror = true;
        setRotation(pouch1, 0.1858931F, 0F, 0F);
        pouch2 = new ModelRenderer(this, 0, 11);
        pouch2.addBox(0F, 0F, -2F, 3, 6, 5);
        pouch2.setRotationPoint(5F, 18.5F, 0F);
        pouch2.setTextureSize(32, 32);
        pouch2.mirror = true;
        setRotation(pouch2, 0F, -0.1115358F, -0.3346075F);
        pouch3 = new ModelRenderer(this, 0, 23);
        pouch3.addBox(0F, 0F, -1F, 4, 5, 3);
        pouch3.setRotationPoint(-8F, 19F, -5F);
        pouch3.setTextureSize(32, 32);
        pouch3.mirror = true;
        setRotation(pouch3, -0.1858931F, 0.6320364F, 0F);
        pouch4 = new ModelRenderer(this, 17, 0);
        pouch4.addBox(0F, 0F, -0.5F, 1, 4, 3);
        pouch4.setRotationPoint(7F, 10F, 3F);
        pouch4.setTextureSize(32, 32);
        pouch4.mirror = true;
        setRotation(pouch4, 0.0371786F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        pouch1.render(f5);
        pouch2.render(f5);
        pouch3.render(f5);
        pouch4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
