/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 30-3-2013 16:26:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeaponRackDetailLeatherWall extends ModelBase
{
    //fields
    ModelRenderer pouch1;
    ModelRenderer pouch2;

    public ModelWeaponRackDetailLeatherWall()
    {
        textureWidth = 32;
        textureHeight = 32;

        pouch1 = new ModelRenderer(this, 0, 0);
        pouch1.addBox(0F, 0F, -1F, 1, 4, 3);
        pouch1.setRotationPoint(-7F, 10F, 6F);
        pouch1.setTextureSize(32, 32);
        pouch1.mirror = true;
        setRotation(pouch1, -0.1115358F, 0.0371786F, 0.1115358F);
        pouch2 = new ModelRenderer(this, 0, 8);
        pouch2.addBox(-2F, 0F, 0F, 4, 5, 2);
        pouch2.setRotationPoint(2F, 9F, 6F);
        pouch2.setTextureSize(32, 32);
        pouch2.mirror = true;
        setRotation(pouch2, -0.0743572F, 0.1487144F, 0.0371786F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        pouch1.render(f5);
        pouch2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
