/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 18-9-2013 19:01:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPedestalIron extends ModelBase
{
    //fields
    ModelRenderer dropthebass;
    ModelRenderer pillar1;
    ModelRenderer pillar2;
    ModelRenderer pillar3;
    ModelRenderer pillar4;
    ModelRenderer top;
    ModelRenderer archpiece1;
    ModelRenderer archpiece2;
    ModelRenderer archpiece3;
    ModelRenderer archpiece4;
    ModelRenderer archpiece5;
    ModelRenderer archpiece6;
    ModelRenderer archpiece7;
    ModelRenderer archpiece8;
    ModelRenderer archpiece9;
    ModelRenderer archpiece10;
    ModelRenderer archpiece11;
    ModelRenderer archpiece12;

    public ModelPedestalIron()
    {
        textureWidth = 128;
        textureHeight = 64;

        dropthebass = new ModelRenderer(this, 0, 0);
        dropthebass.addBox(-6F, 17F, -6F, 12, 2, 12);
        dropthebass.setRotationPoint(0F, 5F, 0F);
        dropthebass.setTextureSize(128, 64);
        dropthebass.mirror = true;
        setRotation(dropthebass, 0F, 0F, 0F);
        pillar1 = new ModelRenderer(this, 0, 28);
        pillar1.addBox(2F, 0F, -4F, 2, 17, 2);
        pillar1.setRotationPoint(0F, 5F, 0F);
        pillar1.setTextureSize(128, 64);
        pillar1.mirror = true;
        setRotation(pillar1, 0F, 0F, 0F);
        pillar2 = new ModelRenderer(this, 9, 28);
        pillar2.addBox(-4F, 0F, -4F, 2, 17, 2);
        pillar2.setRotationPoint(0F, 5F, 0F);
        pillar2.setTextureSize(128, 64);
        pillar2.mirror = true;
        setRotation(pillar2, 0F, 0F, 0F);
        pillar3 = new ModelRenderer(this, 18, 28);
        pillar3.addBox(2F, 0F, 2F, 2, 17, 2);
        pillar3.setRotationPoint(0F, 5F, 0F);
        pillar3.setTextureSize(128, 64);
        pillar3.mirror = true;
        setRotation(pillar3, 0F, 0F, 0F);
        pillar4 = new ModelRenderer(this, 27, 28);
        pillar4.addBox(-4F, 0F, 2F, 2, 17, 2);
        pillar4.setRotationPoint(0F, 5F, 0F);
        pillar4.setTextureSize(128, 64);
        pillar4.mirror = true;
        setRotation(pillar4, 0F, 0F, 0F);
        top = new ModelRenderer(this, 0, 15);
        top.addBox(-5F, -2F, -5F, 10, 2, 10);
        top.setRotationPoint(0F, 5F, 0F);
        top.setTextureSize(128, 64);
        top.mirror = true;
        setRotation(top, 0F, 0F, 0F);
        archpiece1 = new ModelRenderer(this, 0, 48);
        archpiece1.addBox(-2F, 0F, -4F, 4, 2, 1);
        archpiece1.setRotationPoint(0F, 5F, 0F);
        archpiece1.setTextureSize(128, 64);
        archpiece1.mirror = true;
        setRotation(archpiece1, 0F, 0F, 0F);
        archpiece2 = new ModelRenderer(this, 0, 2);
        archpiece2.addBox(1F, 2F, -4F, 1, 1, 1);
        archpiece2.setRotationPoint(0F, 5F, 0F);
        archpiece2.setTextureSize(128, 64);
        archpiece2.mirror = true;
        setRotation(archpiece2, 0F, 0F, 0F);
        archpiece3 = new ModelRenderer(this, 0, 4);
        archpiece3.addBox(-2F, 2F, -4F, 1, 1, 1);
        archpiece3.setRotationPoint(0F, 5F, 0F);
        archpiece3.setTextureSize(128, 64);
        archpiece3.mirror = true;
        setRotation(archpiece3, 0F, 0F, 0F);
        archpiece4 = new ModelRenderer(this, 11, 48);
        archpiece4.addBox(-2F, 0F, 3F, 4, 2, 1);
        archpiece4.setRotationPoint(0F, 5F, 0F);
        archpiece4.setTextureSize(128, 64);
        archpiece4.mirror = true;
        setRotation(archpiece4, 0F, 0F, 0F);
        archpiece5 = new ModelRenderer(this, 0, 6);
        archpiece5.addBox(1F, 2F, 3F, 1, 1, 1);
        archpiece5.setRotationPoint(0F, 5F, 0F);
        archpiece5.setTextureSize(128, 64);
        archpiece5.mirror = true;
        setRotation(archpiece5, 0F, 0F, 0F);
        archpiece6 = new ModelRenderer(this, 0, 8);
        archpiece6.addBox(-2F, 2F, 3F, 1, 1, 1);
        archpiece6.setRotationPoint(0F, 5F, 0F);
        archpiece6.setTextureSize(128, 64);
        archpiece6.mirror = true;
        setRotation(archpiece6, 0F, 0F, 0F);
        archpiece7 = new ModelRenderer(this, 0, 52);
        archpiece7.addBox(3F, 0F, -2F, 1, 2, 4);
        archpiece7.setRotationPoint(0F, 5F, 0F);
        archpiece7.setTextureSize(128, 64);
        archpiece7.mirror = true;
        setRotation(archpiece7, 0F, 0F, 0F);
        archpiece8 = new ModelRenderer(this, 4, 0);
        archpiece8.addBox(3F, 2F, 1F, 1, 1, 1);
        archpiece8.setRotationPoint(0F, 5F, 0F);
        archpiece8.setTextureSize(128, 64);
        archpiece8.mirror = true;
        setRotation(archpiece8, 0F, 0F, 0F);
        archpiece9 = new ModelRenderer(this, 4, 2);
        archpiece9.addBox(3F, 2F, -2F, 1, 1, 1);
        archpiece9.setRotationPoint(0F, 5F, 0F);
        archpiece9.setTextureSize(128, 64);
        archpiece9.mirror = true;
        setRotation(archpiece9, 0F, 0F, 0F);
        archpiece10 = new ModelRenderer(this, 11, 52);
        archpiece10.addBox(-4F, 0F, -2F, 1, 2, 4);
        archpiece10.setRotationPoint(0F, 5F, 0F);
        archpiece10.setTextureSize(128, 64);
        archpiece10.mirror = true;
        setRotation(archpiece10, 0F, 0F, 0F);
        archpiece11 = new ModelRenderer(this, 4, 4);
        archpiece11.addBox(-4F, 2F, -2F, 1, 1, 1);
        archpiece11.setRotationPoint(0F, 5F, 0F);
        archpiece11.setTextureSize(128, 64);
        archpiece11.mirror = true;
        setRotation(archpiece11, 0F, 0F, 0F);
        archpiece12 = new ModelRenderer(this, 0, 0);
        archpiece12.addBox(-4F, 2F, 1F, 1, 1, 1);
        archpiece12.setRotationPoint(0F, 5F, 0F);
        archpiece12.setTextureSize(128, 64);
        archpiece12.mirror = true;
        setRotation(archpiece12, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        dropthebass.render(f5);
        pillar1.render(f5);
        pillar2.render(f5);
        pillar3.render(f5);
        pillar4.render(f5);
        top.render(f5);
        archpiece1.render(f5);
        archpiece2.render(f5);
        archpiece3.render(f5);
        archpiece4.render(f5);
        archpiece5.render(f5);
        archpiece6.render(f5);
        archpiece7.render(f5);
        archpiece8.render(f5);
        archpiece9.render(f5);
        archpiece10.render(f5);
        archpiece11.render(f5);
        archpiece12.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
