/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 15-9-2013 18:32:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGongLarge extends ModelBase
{
    //fields
    ModelRenderer gong1;
    ModelRenderer gong2;
    ModelRenderer gong3;
    ModelRenderer gong4;
    ModelRenderer gong5;
    ModelRenderer gong6;
    ModelRenderer gong7;
    ModelRenderer nipplemid1;
    ModelRenderer nipplemid2;
    ModelRenderer nipplemid3;
    ModelRenderer ultimatenipple;
    ModelRenderer roperight1;
    ModelRenderer ropeleft1;
    ModelRenderer sidenipple1;
    ModelRenderer sidenipple2;
    ModelRenderer sidenipple3;
    ModelRenderer sidenipple4;
    ModelRenderer sidenipple5;
    ModelRenderer sidenipple6;
    ModelRenderer sidenipple7;
    ModelRenderer sidenipple8;
    ModelRenderer ropeleft2;
    ModelRenderer roperight2;
    ModelRenderer ropemid;

    public ModelGongLarge()
    {
        textureWidth = 256;
        textureHeight = 128;

        gong1 = new ModelRenderer(this, 0, 0);
        gong1.addBox(-18F, 0F, -2F, 36, 30, 4);
        gong1.setRotationPoint(0F, -13F, 0F);
        gong1.setTextureSize(256, 128);
        gong1.mirror = true;
        setRotation(gong1, 0F, 0F, 0F);
        gong2 = new ModelRenderer(this, 0, 35);
        gong2.addBox(-15F, -3F, -2F, 30, 3, 4);
        gong2.setRotationPoint(0F, -13F, 0F);
        gong2.setTextureSize(256, 128);
        gong2.mirror = true;
        setRotation(gong2, 0F, 0F, 0F);
        gong3 = new ModelRenderer(this, 0, 43);
        gong3.addBox(-15F, 30F, -2F, 30, 3, 4);
        gong3.setRotationPoint(0F, -13F, 0F);
        gong3.setTextureSize(256, 128);
        gong3.mirror = true;
        setRotation(gong3, 0F, 0F, 0F);
        gong4 = new ModelRenderer(this, 0, 51);
        gong4.addBox(-11F, -5F, -2F, 22, 2, 4);
        gong4.setRotationPoint(0F, -13F, 0F);
        gong4.setTextureSize(256, 128);
        gong4.mirror = true;
        setRotation(gong4, 0F, 0F, 0F);
        gong5 = new ModelRenderer(this, 0, 58);
        gong5.addBox(-11F, 33F, -2F, 22, 2, 4);
        gong5.setRotationPoint(0F, -13F, 0F);
        gong5.setTextureSize(256, 128);
        gong5.mirror = true;
        setRotation(gong5, 0F, 0F, 0F);
        gong6 = new ModelRenderer(this, 81, 0);
        gong6.addBox(-20F, 4F, -2F, 2, 22, 4);
        gong6.setRotationPoint(0F, -13F, 0F);
        gong6.setTextureSize(256, 128);
        gong6.mirror = true;
        setRotation(gong6, 0F, 0F, 0F);
        gong7 = new ModelRenderer(this, 94, 0);
        gong7.addBox(18F, 4F, -2F, 2, 22, 4);
        gong7.setRotationPoint(0F, -13F, 0F);
        gong7.setTextureSize(256, 128);
        gong7.mirror = true;
        setRotation(gong7, 0F, 0F, 0F);
        nipplemid1 = new ModelRenderer(this, 81, 27);
        nipplemid1.addBox(-4F, 9F, -2.5F, 8, 12, 5);
        nipplemid1.setRotationPoint(0F, -13F, 0F);
        nipplemid1.setTextureSize(256, 128);
        nipplemid1.mirror = true;
        setRotation(nipplemid1, 0F, 0F, 0F);
        nipplemid2 = new ModelRenderer(this, 107, 0);
        nipplemid2.addBox(-6F, 11F, -2.5F, 2, 8, 5);
        nipplemid2.setRotationPoint(0F, -13F, 0F);
        nipplemid2.setTextureSize(256, 128);
        nipplemid2.mirror = true;
        setRotation(nipplemid2, 0F, 0F, 0F);
        nipplemid3 = new ModelRenderer(this, 107, 14);
        nipplemid3.addBox(4F, 11F, -2.5F, 2, 8, 5);
        nipplemid3.setRotationPoint(0F, -13F, 0F);
        nipplemid3.setTextureSize(256, 128);
        nipplemid3.mirror = true;
        setRotation(nipplemid3, 0F, 0F, 0F);
        ultimatenipple = new ModelRenderer(this, 122, 0);
        ultimatenipple.addBox(-2F, 13F, -3.5F, 4, 4, 7);
        ultimatenipple.setRotationPoint(0F, -13F, 0F);
        ultimatenipple.setTextureSize(256, 128);
        ultimatenipple.mirror = true;
        setRotation(ultimatenipple, 0F, 0F, 0F);
        roperight1 = new ModelRenderer(this, 0, 75);
        roperight1.addBox(-1F, 0F, -1F, 2, 13, 2);
        roperight1.setRotationPoint(-20F, -24.5F, 0F);
        roperight1.setTextureSize(256, 128);
        roperight1.mirror = true;
        setRotation(roperight1, 0F, 0F, -0.2974289F);
        ropeleft1 = new ModelRenderer(this, 10, 75);
        ropeleft1.addBox(-1F, 0F, -1F, 2, 13, 2);
        ropeleft1.setRotationPoint(20F, -24.5F, 0F);
        ropeleft1.setTextureSize(256, 128);
        ropeleft1.mirror = true;
        setRotation(ropeleft1, 0F, 0F, 0.2974216F);
        sidenipple1 = new ModelRenderer(this, 150, 0);
        sidenipple1.addBox(6.5F, 5.5F, -3F, 3, 3, 6);
        sidenipple1.setRotationPoint(0F, -13F, 0F);
        sidenipple1.setTextureSize(256, 128);
        sidenipple1.mirror = true;
        setRotation(sidenipple1, 0F, 0F, 0F);
        sidenipple2 = new ModelRenderer(this, 150, 10);
        sidenipple2.addBox(-1.5F, 3F, -3F, 3, 3, 6);
        sidenipple2.setRotationPoint(0F, -13F, 0F);
        sidenipple2.setTextureSize(256, 128);
        sidenipple2.mirror = true;
        setRotation(sidenipple2, 0F, 0F, 0F);
        sidenipple3 = new ModelRenderer(this, 150, 20);
        sidenipple3.addBox(-9.5F, 5.5F, -3F, 3, 3, 6);
        sidenipple3.setRotationPoint(0F, -13F, 0F);
        sidenipple3.setTextureSize(256, 128);
        sidenipple3.mirror = true;
        setRotation(sidenipple3, 0F, 0F, 0F);
        sidenipple4 = new ModelRenderer(this, 150, 30);
        sidenipple4.addBox(9F, 13.5F, -3F, 3, 3, 6);
        sidenipple4.setRotationPoint(0F, -13F, 0F);
        sidenipple4.setTextureSize(256, 128);
        sidenipple4.mirror = true;
        setRotation(sidenipple4, 0F, 0F, 0F);
        sidenipple5 = new ModelRenderer(this, 150, 40);
        sidenipple5.addBox(-12F, 13.5F, -3F, 3, 3, 6);
        sidenipple5.setRotationPoint(0F, -13F, 0F);
        sidenipple5.setTextureSize(256, 128);
        sidenipple5.mirror = true;
        setRotation(sidenipple5, 0F, 0F, 0F);
        sidenipple6 = new ModelRenderer(this, 150, 50);
        sidenipple6.addBox(6.5F, 21.5F, -3F, 3, 3, 6);
        sidenipple6.setRotationPoint(0F, -13F, 0F);
        sidenipple6.setTextureSize(256, 128);
        sidenipple6.mirror = true;
        setRotation(sidenipple6, 0F, 0F, 0F);
        sidenipple7 = new ModelRenderer(this, 150, 60);
        sidenipple7.addBox(-9.5F, 21.5F, -3F, 3, 3, 6);
        sidenipple7.setRotationPoint(0F, -13F, 0F);
        sidenipple7.setTextureSize(256, 128);
        sidenipple7.mirror = true;
        setRotation(sidenipple7, 0F, 0F, 0F);
        sidenipple8 = new ModelRenderer(this, 150, 70);
        sidenipple8.addBox(-1.5F, 24F, -3F, 3, 3, 6);
        sidenipple8.setRotationPoint(0F, -13F, 0F);
        sidenipple8.setTextureSize(256, 128);
        sidenipple8.mirror = true;
        setRotation(sidenipple8, 0F, 0F, 0F);
        ropeleft2 = new ModelRenderer(this, 0, 92);
        ropeleft2.addBox(-0.5F, 0F, -0.5F, 1, 8, 1);
        ropeleft2.setRotationPoint(8F, -24.5F, 0F);
        ropeleft2.setTextureSize(256, 128);
        ropeleft2.mirror = true;
        setRotation(ropeleft2, 0F, 0F, 0.1487144F);
        roperight2 = new ModelRenderer(this, 5, 92);
        roperight2.addBox(-0.5F, 0F, -0.5F, 1, 8, 1);
        roperight2.setRotationPoint(-8F, -24.5F, 0F);
        roperight2.setTextureSize(256, 128);
        roperight2.mirror = true;
        setRotation(roperight2, 0F, 0F, -0.1487195F);
        ropemid = new ModelRenderer(this, 0, 103);
        ropemid.addBox(-19F, 0F, 0F, 38, 9, 0);
        ropemid.setRotationPoint(0F, -24.5F, 0F);
        ropemid.setTextureSize(256, 128);
        ropemid.mirror = true;
        setRotation(ropemid, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        gong1.render(f5);
        gong2.render(f5);
        gong3.render(f5);
        gong4.render(f5);
        gong5.render(f5);
        gong6.render(f5);
        gong7.render(f5);
        nipplemid1.render(f5);
        nipplemid2.render(f5);
        nipplemid3.render(f5);
        ultimatenipple.render(f5);
        roperight1.render(f5);
        ropeleft1.render(f5);
        sidenipple1.render(f5);
        sidenipple2.render(f5);
        sidenipple3.render(f5);
        sidenipple4.render(f5);
        sidenipple5.render(f5);
        sidenipple6.render(f5);
        sidenipple7.render(f5);
        sidenipple8.render(f5);
        ropeleft2.render(f5);
        roperight2.render(f5);
        ropemid.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
    {
        gong1.rotateAngleY = par7Entity.rotationYaw;
        gong2.rotateAngleY = par7Entity.rotationYaw;
        gong3.rotateAngleY = par7Entity.rotationYaw;
        gong4.rotateAngleY = par7Entity.rotationYaw;
        gong5.rotateAngleY = par7Entity.rotationYaw;
        gong6.rotateAngleY = par7Entity.rotationYaw;
        gong7.rotateAngleY = par7Entity.rotationYaw;
        nipplemid1.rotateAngleY = par7Entity.rotationYaw;
        nipplemid2.rotateAngleY = par7Entity.rotationYaw;
        nipplemid3.rotateAngleY = par7Entity.rotationYaw;
        ultimatenipple.rotateAngleY = par7Entity.rotationYaw;
        sidenipple1.rotateAngleY = par7Entity.rotationYaw;
        sidenipple2.rotateAngleY = par7Entity.rotationYaw;
        sidenipple3.rotateAngleY = par7Entity.rotationYaw;
        sidenipple4.rotateAngleY = par7Entity.rotationYaw;
        sidenipple5.rotateAngleY = par7Entity.rotationYaw;
        sidenipple6.rotateAngleY = par7Entity.rotationYaw;
        sidenipple7.rotateAngleY = par7Entity.rotationYaw;
        sidenipple8.rotateAngleY = par7Entity.rotationYaw;

        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }
}
