/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 29-3-2013 20:15:57
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeaponRackDetailMushrooms extends ModelBase
{
    //fields
    ModelRenderer stem1;
    ModelRenderer hat1;
    ModelRenderer stem2;
    ModelRenderer hat2;
    ModelRenderer hat3;
    ModelRenderer tinder1;
    ModelRenderer tinder2;
    ModelRenderer tinder3;
    ModelRenderer stem3;
    ModelRenderer hat4;

    public ModelWeaponRackDetailMushrooms()
    {
        textureWidth = 32;
        textureHeight = 32;

        stem1 = new ModelRenderer(this, 0, 0);
        stem1.addBox(0F, -3F, 0F, 1, 3, 1);
        stem1.setRotationPoint(6F, 24F, -6F);
        stem1.setTextureSize(32, 32);
        stem1.mirror = true;
        setRotation(stem1, 0.4089647F, -0.3717861F, 0F);
        hat1 = new ModelRenderer(this, 0, 6);
        hat1.addBox(-0.5F, -4.5F, -1.5F, 2, 2, 2);
        hat1.setRotationPoint(6F, 24F, -6F);
        hat1.setTextureSize(32, 32);
        hat1.mirror = true;
        setRotation(hat1, 0.1115358F, -0.37179F, -0.0371786F);
        stem2 = new ModelRenderer(this, 5, 0);
        stem2.addBox(0F, -2F, 0F, 1, 2, 1);
        stem2.setRotationPoint(4.5F, 24F, -6F);
        stem2.setTextureSize(32, 32);
        stem2.mirror = true;
        setRotation(stem2, 0F, -0.5205006F, -0.2602503F);
        hat2 = new ModelRenderer(this, 9, 6);
        hat2.addBox(-1F, -3F, -0.5F, 2, 1, 2);
        hat2.setRotationPoint(4.5F, 24F, -6F);
        hat2.setTextureSize(32, 32);
        hat2.mirror = true;
        setRotation(hat2, 0F, -0.5204921F, 0F);
        hat3 = new ModelRenderer(this, 18, 6);
        hat3.addBox(0F, -1F, 0F, 1, 1, 1);
        hat3.setRotationPoint(4F, 24F, -7F);
        hat3.setTextureSize(32, 32);
        hat3.mirror = true;
        setRotation(hat3, 0.2602503F, 0.1487144F, 0F);
        tinder1 = new ModelRenderer(this, 0, 12);
        tinder1.addBox(0F, 0F, 0F, 3, 1, 2);
        tinder1.setRotationPoint(5F, 17F, 5F);
        tinder1.setTextureSize(32, 32);
        tinder1.mirror = true;
        setRotation(tinder1, -0.1115358F, 0.5948578F, 0F);
        tinder2 = new ModelRenderer(this, 11, 12);
        tinder2.addBox(0F, 0F, 0F, 2, 1, 2);
        tinder2.setRotationPoint(4.5F, 15F, 4F);
        tinder2.setTextureSize(32, 32);
        tinder2.mirror = true;
        setRotation(tinder2, -0.1115358F, -0.1115358F, 0F);
        tinder3 = new ModelRenderer(this, 20, 12);
        tinder3.addBox(1F, 0F, 0F, 2, 1, 2);
        tinder3.setRotationPoint(5F, 13F, 5.5F);
        tinder3.setTextureSize(32, 32);
        tinder3.mirror = true;
        setRotation(tinder3, -0.0743572F, 0.9666439F, 0F);
        stem3 = new ModelRenderer(this, 0, 16);
        stem3.addBox(0F, -4F, 0F, 1, 4, 1);
        stem3.setRotationPoint(-4F, 24F, 7F);
        stem3.setTextureSize(32, 32);
        stem3.mirror = true;
        setRotation(stem3, -0.2974289F, 0.2974289F, 0F);
        hat4 = new ModelRenderer(this, 0, 22);
        hat4.addBox(-1F, -5F, 0F, 3, 2, 3);
        hat4.setRotationPoint(-4F, 24F, 7F);
        hat4.setTextureSize(32, 32);
        hat4.mirror = true;
        setRotation(hat4, 0F, 0.2974216F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        stem1.render(f5);
        hat1.render(f5);
        stem2.render(f5);
        hat2.render(f5);
        hat3.render(f5);
        tinder1.render(f5);
        tinder2.render(f5);
        tinder3.render(f5);
        stem3.render(f5);
        hat4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
