/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 15-9-2013 17:44:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGongMedium extends ModelBase
{
    //fields
    ModelRenderer gong1;
    ModelRenderer gong2;
    ModelRenderer gong3;
    ModelRenderer gong4;
    ModelRenderer gong5;
    ModelRenderer nipple;
    ModelRenderer roperight;
    ModelRenderer ropeleft;
    ModelRenderer ropemid;

    public ModelGongMedium()
    {
        textureWidth = 128;
        textureHeight = 64;

        gong1 = new ModelRenderer(this, 0, 0);
        gong1.addBox(-10F, 0F, -1.5F, 20, 20, 3);
        gong1.setRotationPoint(8F, 0F, 0F);
        gong1.setTextureSize(128, 64);
        gong1.mirror = true;
        setRotation(gong1, 0F, 0F, 0F);
        gong2 = new ModelRenderer(this, 0, 24);
        gong2.addBox(-7F, -2F, -1.5F, 14, 2, 3);
        gong2.setRotationPoint(8F, 0F, 0F);
        gong2.setTextureSize(128, 64);
        gong2.mirror = true;
        setRotation(gong2, 0F, 0F, 0F);
        gong3 = new ModelRenderer(this, 0, 30);
        gong3.addBox(-7F, 20F, -1.5F, 14, 2, 3);
        gong3.setRotationPoint(8F, 0F, 0F);
        gong3.setTextureSize(128, 64);
        gong3.mirror = true;
        setRotation(gong3, 0F, 0F, 0F);
        gong4 = new ModelRenderer(this, 0, 36);
        gong4.addBox(-12F, 3F, -1.5F, 2, 14, 3);
        gong4.setRotationPoint(8F, 0F, 0F);
        gong4.setTextureSize(128, 64);
        gong4.mirror = true;
        setRotation(gong4, 0F, 0F, 0F);
        gong5 = new ModelRenderer(this, 11, 36);
        gong5.addBox(10F, 3F, -1.5F, 2, 14, 3);
        gong5.setRotationPoint(8F, 0F, 0F);
        gong5.setTextureSize(128, 64);
        gong5.mirror = true;
        setRotation(gong5, 0F, 0F, 0F);
        nipple = new ModelRenderer(this, 22, 36);
        nipple.addBox(-2F, 8F, -2F, 4, 4, 4);
        nipple.setRotationPoint(8F, 0F, 0F);
        nipple.setTextureSize(128, 64);
        nipple.mirror = true;
        setRotation(nipple, 0F, 0F, 0F);
        roperight = new ModelRenderer(this, 60, 0);
        roperight.addBox(-0.5F, 0F, -0.5F, 1, 10, 1);
        roperight.setRotationPoint(-4F, -9F, 0F);
        roperight.setTextureSize(128, 64);
        roperight.mirror = true;
        setRotation(roperight, 0F, 0F, -0.3346075F);
        ropeleft = new ModelRenderer(this, 65, 0);
        ropeleft.addBox(-0.5F, 0F, -0.5F, 1, 10, 1);
        ropeleft.setRotationPoint(20F, -9F, 0F);
        ropeleft.setTextureSize(128, 64);
        ropeleft.mirror = true;
        setRotation(ropeleft, 0F, 0F, 0.3346145F);
        ropemid = new ModelRenderer(this, 60, 12);
        ropemid.addBox(-12F, 0F, 0F, 24, 7, 0);
        ropemid.setRotationPoint(8F, -9F, 0F);
        ropemid.setTextureSize(128, 64);
        ropemid.mirror = true;
        setRotation(ropemid, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        gong1.render(f5);
        gong2.render(f5);
        gong3.render(f5);
        gong4.render(f5);
        gong5.render(f5);
        nipple.render(f5);
        roperight.render(f5);
        ropeleft.render(f5);
        ropemid.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @Override
    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
    {
        gong1.rotateAngleY = par7Entity.rotationYaw;
        gong2.rotateAngleY = par7Entity.rotationYaw;
        gong3.rotateAngleY = par7Entity.rotationYaw;
        gong4.rotateAngleY = par7Entity.rotationYaw;
        gong5.rotateAngleY = par7Entity.rotationYaw;
        nipple.rotateAngleY = par7Entity.rotationYaw;

        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }
}
