/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 30-3-2013 15:59:54
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeaponRackDetailBonemealWall extends ModelBase
{
    //fields
    ModelRenderer moss1;
    ModelRenderer moss2;
    ModelRenderer plant;
    ModelRenderer greenstuff;

    public ModelWeaponRackDetailBonemealWall()
    {
        textureWidth = 32;
        textureHeight = 32;

        moss1 = new ModelRenderer(this, 0, 0);
        moss1.addBox(-3F, -0.1F, -0.1F, 10, 0, 3);
        moss1.setRotationPoint(0F, 14F, 4F);
        moss1.setTextureSize(32, 32);
        moss1.mirror = true;
        setRotation(moss1, 0F, 0F, 0F);
        moss2 = new ModelRenderer(this, 0, 4);
        moss2.addBox(-3F, -0.1F, -0.1F, 10, 6, 0);
        moss2.setRotationPoint(0F, 14F, 4F);
        moss2.setTextureSize(32, 32);
        moss2.mirror = true;
        setRotation(moss2, 0F, 0F, 0F);
        plant = new ModelRenderer(this, 0, 11);
        plant.addBox(-0.1F, 0F, -0.1F, 2, 9, 2);
        plant.setRotationPoint(-6F, 16F, 6F);
        plant.setTextureSize(32, 32);
        plant.mirror = true;
        setRotation(plant, 0F, 0F, 0F);
        greenstuff = new ModelRenderer(this, 0, 23);
        greenstuff.addBox(-7F, -0.1F, 0F, 10, 0, 3);
        greenstuff.setRotationPoint(0F, 22F, 4F);
        greenstuff.setTextureSize(32, 32);
        greenstuff.mirror = true;
        setRotation(greenstuff, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        moss1.render(f5);
        moss2.render(f5);
        plant.render(f5);
        greenstuff.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
