/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 17-9-2013 19:57:04
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPedestalStoneBlock extends ModelBase
{
    //fields
    ModelRenderer base;
    ModelRenderer mid;
    ModelRenderer top;
    ModelRenderer corner1;
    ModelRenderer corner2;
    ModelRenderer corner3;
    ModelRenderer corner4;
    ModelRenderer holder2;

    public ModelPedestalStoneBlock()
    {
        textureWidth = 128;
        textureHeight = 64;

        base = new ModelRenderer(this, 0, 0);
        base.addBox(-7F, 13F, -7F, 14, 3, 14);
        base.setRotationPoint(0F, 8F, 0F);
        base.setTextureSize(128, 64);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        mid = new ModelRenderer(this, 0, 18);
        mid.addBox(-3F, 0F, -3F, 6, 13, 6);
        mid.setRotationPoint(0F, 8F, 0F);
        mid.setTextureSize(128, 64);
        mid.mirror = true;
        setRotation(mid, 0F, 0F, 0F);
        top = new ModelRenderer(this, 0, 38);
        top.addBox(-6F, -3F, -6F, 12, 3, 12);
        top.setRotationPoint(0F, 8F, 0F);
        top.setTextureSize(128, 64);
        top.mirror = true;
        setRotation(top, 0F, 0F, 0F);
        corner1 = new ModelRenderer(this, 70, 0);
        corner1.addBox(2F, 0F, -3.533333F, 2, 13, 2);
        corner1.setRotationPoint(0F, 8F, 0F);
        corner1.setTextureSize(128, 64);
        corner1.mirror = true;
        setRotation(corner1, 0F, 0F, 0F);
        corner2 = new ModelRenderer(this, 70, 16);
        corner2.addBox(-4F, 0F, -4F, 2, 13, 2);
        corner2.setRotationPoint(0F, 8F, 0F);
        corner2.setTextureSize(128, 64);
        corner2.mirror = true;
        setRotation(corner2, 0F, 0F, 0F);
        corner3 = new ModelRenderer(this, 70, 32);
        corner3.addBox(2F, 0F, 2F, 2, 13, 2);
        corner3.setRotationPoint(0F, 8F, 0F);
        corner3.setTextureSize(128, 64);
        corner3.mirror = true;
        setRotation(corner3, 0F, 0F, 0F);
        corner4 = new ModelRenderer(this, 70, 48);
        corner4.addBox(-4F, 0F, 2F, 2, 13, 2);
        corner4.setRotationPoint(0F, 8F, 0F);
        corner4.setTextureSize(128, 64);
        corner4.mirror = true;
        setRotation(corner4, 0F, 0F, 0F);
        holder2 = new ModelRenderer(this, 24, 8);
        holder2.addBox(-3F, -8F, -3F, 6, 2, 6);
        holder2.setRotationPoint(0F, 11F, 0F);
        holder2.setTextureSize(128, 64);
        holder2.mirror = true;
        setRotation(holder2, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        base.render(f5);
        mid.render(f5);
        top.render(f5);
        corner1.render(f5);
        corner2.render(f5);
        corner3.render(f5);
        corner4.render(f5);
        holder2.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
