/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 29-3-2013 23:07:01
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeaponRackDetailCobweb extends ModelBase
{
    //fields
    ModelRenderer cobweb1;
    ModelRenderer cobweb2;
    ModelRenderer cobweb3;

    public ModelWeaponRackDetailCobweb()
    {
        textureWidth = 32;
        textureHeight = 32;

        cobweb1 = new ModelRenderer(this, 0, 0);
        cobweb1.addBox(0F, 0F, 0F, 7, 7, 0);
        cobweb1.setRotationPoint(-5F, 14F, -4.5F);
        cobweb1.setTextureSize(32, 32);
        cobweb1.mirror = true;
        setRotation(cobweb1, 0F, 0F, 0F);
        cobweb2 = new ModelRenderer(this, 0, 8);
        cobweb2.addBox(0F, 0F, 0F, 4, 0, 4);
        cobweb2.setRotationPoint(-6F, 9F, -4F);
        cobweb2.setTextureSize(32, 32);
        cobweb2.mirror = true;
        setRotation(cobweb2, -0.2230717F, 0F, 0.0743572F);
        cobweb3 = new ModelRenderer(this, 0, 13);
        cobweb3.addBox(0F, 0F, -3F, 0, 6, 6);
        cobweb3.setRotationPoint(6.5F, 11F, 0F);
        cobweb3.setTextureSize(32, 32);
        cobweb3.mirror = true;
        setRotation(cobweb3, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        cobweb1.render(f5);
        cobweb2.render(f5);
        cobweb3.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
