/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 30-3-2013 16:16:02
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWeaponRackDetailMushroomsWall extends ModelBase
{
    //fields
    ModelRenderer tinder1;
    ModelRenderer tinder2;
    ModelRenderer tinder3;
    ModelRenderer tinder4;
    ModelRenderer shroom1;
    ModelRenderer shroom2;
    ModelRenderer shroom3;
    ModelRenderer shroom4;

    public ModelWeaponRackDetailMushroomsWall()
    {
        textureWidth = 32;
        textureHeight = 32;

        tinder1 = new ModelRenderer(this, 0, 0);
        tinder1.addBox(-1.2F, -1F, -1F, 2, 1, 2);
        tinder1.setRotationPoint(6F, 13.5F, 6F);
        tinder1.setTextureSize(32, 32);
        tinder1.mirror = true;
        setRotation(tinder1, 0.1115358F, -0.6320364F, 0F);
        tinder2 = new ModelRenderer(this, 0, 8);
        tinder2.addBox(-1F, 1F, -1F, 2, 1, 3);
        tinder2.setRotationPoint(6F, 15F, 6F);
        tinder2.setTextureSize(32, 32);
        tinder2.mirror = true;
        setRotation(tinder2, -0.0371786F, 0.4833219F, 0.1487144F);
        tinder3 = new ModelRenderer(this, 0, 4);
        tinder3.addBox(-1F, 0F, 0F, 2, 1, 2);
        tinder3.setRotationPoint(6F, 14.5F, 6F);
        tinder3.setTextureSize(32, 32);
        tinder3.mirror = true;
        setRotation(tinder3, 0F, 0.4461433F, 0F);
        tinder4 = new ModelRenderer(this, 0, 13);
        tinder4.addBox(-1F, 0F, -1.5F, 2, 1, 2);
        tinder4.setRotationPoint(6F, 18F, 6F);
        tinder4.setTextureSize(32, 32);
        tinder4.mirror = true;
        setRotation(tinder4, 0F, 1.33843F, 0.0743572F);
        shroom1 = new ModelRenderer(this, 15, 0);
        shroom1.addBox(0F, 0F, -1F, 1, 1, 1);
        shroom1.setRotationPoint(-6F, 21F, 6F);
        shroom1.setTextureSize(32, 32);
        shroom1.mirror = true;
        setRotation(shroom1, 0.2602503F, 0.5576792F, 0F);
        shroom2 = new ModelRenderer(this, 15, 3);
        shroom2.addBox(-1F, 0F, 0F, 1, 1, 1);
        shroom2.setRotationPoint(-6F, 21F, 6F);
        shroom2.setTextureSize(32, 32);
        shroom2.mirror = true;
        setRotation(shroom2, -0.1115358F, 0.2230717F, 0.0371786F);
        shroom3 = new ModelRenderer(this, 15, 6);
        shroom3.addBox(0F, 0F, -1F, 1, 1, 1);
        shroom3.setRotationPoint(-7F, 21F, 5F);
        shroom3.setTextureSize(32, 32);
        shroom3.mirror = true;
        setRotation(shroom3, 0.5205006F, 0.4833219F, 0F);
        shroom4 = new ModelRenderer(this, 15, 9);
        shroom4.addBox(1F, 0F, 0F, 1, 1, 1);
        shroom4.setRotationPoint(-5F, 21F, 5F);
        shroom4.setTextureSize(32, 32);
        shroom4.mirror = true;
        setRotation(shroom4, 0F, 0.3717861F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        tinder1.render(f5);
        tinder2.render(f5);
        tinder3.render(f5);
        tinder4.render(f5);
        shroom1.render(f5);
        shroom2.render(f5);
        shroom3.render(f5);
        shroom4.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
