/***************************************************************************************************
 * Copyright (c) 2014, Lukas Tenbrink.
 * http://lukas.axxim.net
 **************************************************************************************************/

// Date: 17-9-2013 19:10:00
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package ivorius.yegamolchattels.client.rendering;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPedestalWood extends ModelBase
{
    //fields
    ModelRenderer mid;
    ModelRenderer base;
    ModelRenderer top;

    public ModelPedestalWood()
    {
        textureWidth = 128;
        textureHeight = 64;

        mid = new ModelRenderer(this, 0, 0);
        mid.addBox(-5F, 0F, -5F, 10, 11, 10);
        mid.setRotationPoint(0F, 10F, 0F);
        mid.setTextureSize(128, 64);
        mid.mirror = true;
        setRotation(mid, 0F, 0F, 0F);
        base = new ModelRenderer(this, 41, 0);
        base.addBox(-7F, 18F, -7F, 14, 3, 14);
        base.setRotationPoint(0F, 3F, 0F);
        base.setTextureSize(128, 64);
        base.mirror = true;
        setRotation(base, 0F, 0F, 0F);
        top = new ModelRenderer(this, 41, 18);
        top.addBox(-7F, -3F, -7F, 14, 3, 14);
        top.setRotationPoint(0F, 10F, 0F);
        top.setTextureSize(128, 64);
        top.mirror = true;
        setRotation(top, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
    {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        mid.render(f5);
        base.render(f5);
        top.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
